setupper/event_cal/urls.py
from django.conf.urls import url
import datetime

from . import views

today = datetime.date.today()


app_name = 'event_cal'
urlpatterns = [
    # eg: /event_cal/
    url(r'^$', views.event_cal, name='index'),
    # eg: /event_cal/HCC/2016/02/25
    url(r'^(?P<building>[\w]+)/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/(?P<day>[0-9]{1,2})/$', views.event_cal, name='event_cal_full'),
    # eg: /event_cal/HCC/  (no date, should default to today)
    url(r'^(?P<building>[\w]+)/$', views.event_cal, {'year': today.year, 'month': today.month, 'day': today.day}, name='event_cal_short'),
]

setupper/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

setupper/row_config/urls.py
from django.conf.urls import url

from . import views

app_name = 'row_config'
urlpatterns = [
    # Goes to building selection screen
    url(r'^$', views.row_config, name='index'),
    
    url(r'^(?P<building>[\w]+)/$', views.row_config, name='row_config')
]

setupper/setupper/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^event_cal/', include('event_cal.urls')),
    url(r'^row_config/', include('row_config.urls')),
    url(r'^admin/', admin.site.urls),
]

setupper/event_cal/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Building(models.Model):
    name = models.CharField(max_length=256)
    name_short = models.CharField(max_length=10)
    def __str__(self):
        return '{0} ({1})'.format(self.name, self.name_short)

class Room(models.Model):
    name = models.CharField(max_length=50)
    building = models.ForeignKey(Building, on_delete=models.PROTECT)
    row_top = models.IntegerField()
    row_bottom = models.IntegerField()
    label = models.BooleanField
    def __str__(self):
        return self.name

class Event(models.Model):
    name = models.CharField(max_length=256)
    number = models.CharField(max_length=5)
    def __str__(self):
        return self.name

class Resource(models.Model):
    name = models.CharField(max_length=256)
    def __str__(self):
        return self.name

class Colour(models.Model):
    name = models.CharField(max_length=50)
    hex_value = models.CharField(max_length=6)     # Hex RGB value
    def __str__(self):
        return '{0} ({1})'.format(self.name, self.hex_value)

class User(models.Model):
    name = models.CharField(max_length=50)
    colour = models.ForeignKey(Colour, on_delete=models.PROTECT)     # Hex RGB value
    def __str__(self):
        return self.name

class OrderType(models.Model):
    name = models.CharField(max_length=256)
    def __str__(self):
        return self.name

class Note(models.Model):
    note = models.TextField()

class Setup(models.Model):
    time_start = models.DateTimeField()
    time_end = models.DateTimeField()
    room = models.ForeignKey(Room, on_delete=models.PROTECT)
    event = models.ForeignKey(Event, on_delete=models.PROTECT)
    resource = models.ForeignKey(Resource, on_delete=models.PROTECT)
    quantity = models.IntegerField()
    order_type = models.ForeignKey(OrderType, on_delete=models.PROTECT)
    setup_by = models.ForeignKey(User, on_delete=models.PROTECT, null=True, related_name='setups')
    setup_time = models.DateTimeField(null=True)
    pickup_by = models.ForeignKey(User, on_delete=models.PROTECT, null=True, related_name='pickups')
    pickup_time = models.DateTimeField(null=True)
    note = models.ForeignKey(Note, on_delete=models.SET_NULL, null=True)

setupper/polls/models.py
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

setupper/row_config/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

setupper/event_cal/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.template import loader


# Create your views here.

def event_cal(request, building, year, month, day):
    return HttpResponse("{0}, {1}-{2}-{3}".format(building, year, month, day))

def upload(request):
    return HttpResponse("This will be the upload page")

setupper/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.template import loader

from models import Question
# Create your views here.

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

setupper/row_config/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.core import serializers

from event_cal.models import Room, Building

# Create your views here.

def row_config(request, building):
    this_building = Building.objects.get(name_short=building)
    # room_list = Room.objects.filter(building=this_building)
    room_list = serializers.serialize('json', Room.objects.filter(building=this_building))
    template = loader.get_template('row_config/row_config.html')
    context = {
        'building': building,
        'room_list': room_list
    }
    return HttpResponse(template.render(context, request))

setupper/event_cal/templates/event_cal/index.html
<html>
<head>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'event_cal/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static 'event_cal/scrollSync.js' %}"></script>
</head>

<body>
    <div id="header">
        <div id="header_building">
            <h2 class="header">{{ building }}</h2>
        </div>
        <div id="header_date">
            <h1 class="header">{{ year }}-{{ month }}-{{ day }}</h1>
        </div>
        <div id="header_username">
            <h2 class="header">Galen Elfert</h2>
        </div>
    </div>
    
    <div id="bar">
        <div id="bar_room">Room</div>
        <div id="bar_time">
            <table id="bar_time_table">
                <tr id="bar_time_table_row">
                    <td><div class="bar_time_table_elem">06:00</div></td>
                    <td><div class="bar_time_table_elem">06:30</div></td>
                    <td><div class="bar_time_table_elem">07:00</div></td>
                    <td><div class="bar_time_table_elem">07:30</div></td>
                    <td><div class="bar_time_table_elem">08:00</div></td>
                    <td><div class="bar_time_table_elem">08:30</div></td>
                    <td><div class="bar_time_table_elem">09:00</div></td>
                    <td><div class="bar_time_table_elem">09:30</div></td>
                    <td><div class="bar_time_table_elem">10:00</div></td>
                    <td><div class="bar_time_table_elem">10:30</div></td>
                    <td><div class="bar_time_table_elem">11:00</div></td>
                    <td><div class="bar_time_table_elem">11:30</div></td>
                    <td><div class="bar_time_table_elem">12:00</div></td>
                    <td><div class="bar_time_table_elem">12:30</div></td>
                    <td><div class="bar_time_table_elem">13:00</div></td>
                    <td><div class="bar_time_table_elem">13:30</div></td>
                    <td><div class="bar_time_table_elem">14:00</div></td>
                    <td><div class="bar_time_table_elem">14:30</div></td>
                    <td><div class="bar_time_table_elem">15:00</div></td>
                    <td><div class="bar_time_table_elem">15:30</div></td>
                </tr>
            </table>
        </div>
    </div>
    
    <div id="body">
        <div id="body_left">
            <div class="room_table_elem"><h2>1315</h2></div>
            <div class="room_table_elem"><h2>1325</h2></div>
            <div class="room_table_elem"><h2>1350</h2></div>
            <div class="room_table_elem"><h2>1400</h2></div>
            <div class="room_table_elem"><h2>1410</h2></div>
            <div class="room_table_elem"><h2>1420</h2></div>
            <div class="room_table_elem"><h2>1430</h2></div>
            <div class="room_table_elem"><h2>1415</h2></div>
            <div class="room_table_elem"><h2>1425</h2></div>
            <div class="room_table_elem"><h2>1500</h2></div>
            <div class="room_table_elem"><h2>1510</h2></div>
            <div class="room_table_elem"><h2>1520</h2></div>
            <div class="room_table_elem"><h2>1530</h2></div>
        </div>
        
        <div id="body_right">
            <div id="body_right_content">
                <div id="time_line"></div>
                <div class="event picked" id="event01">
                    <h1>Event 1</h1>
                    <ul>
                        
                    </ul>
                </div>
                <div class="event part_picked" id="event02"><h1>Event 2</h1></div>
                <div class="event set" id="event03"><h1>Event 3</h1></div>
                <div class="event part_set" id="event04"><h1>Event 4</h1></div>
                <div class="event no_set" id="event05"><h1>Event 5</h1></div>
                <div class="row"></div>
                <div class="row"></div>
                <div class="row"></div>
                <div class="row"></div>
                <div class="row"></div>
                <div class="row"></div>
                <div class="row"></div>
                <div class="row"></div>
                <div class="row"></div>
                <div class="row"></div>
                <div class="row"></div>
                <div class="row"></div>
            </div>
        </div>
    </div>

<div id="bg_fade"></div>
    
</body>
</html>

setupper/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

setupper/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

setupper/row_config/templates/row_config/row_config.html
<html>
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'row_config/style.css' %}" type="text/css" media="all" />
    <script type="text/javascript" src="{% static 'interact/interact.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'react/react-with-addons.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'react/react-dom.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'row_config/RC_react.js' %}" charset="utf-8"></script>
</head>
<body>
    <div id="container">
        React failed to load
    </div>
    <script type="text/javascript" charset="utf-8">
        var rooms = {{room_list|safe}}; 
        rooms.sort(function(a, b) {
            if (a.fields.name > b.fields.name) return 1;
            else if (a.fields.name < b.fields.name) return -1;
            else return 0;
        });

        var appRef = ReactDOM.render(
          React.createElement(RowTable, {rooms: rooms}),
          document.getElementById('container')
        );

        // Interact
        var snapSettings = {
                targets: [ 
                    interact.createSnapGrid({ x: 40, y: 40 }) 
                ],
          range: Infinity,
        };

        interact('.slider')
            .draggable({
                snap: snapSettings, 
                restrict: {
                    restriction: 'parent', 
                    endOnly: false,
                },
                autoscroll: true, 
                onmove: dragMoveListener
            })
            .resizable({
                snap: snapSettings,
                edges: { left: false, right: false, bottom: true, top: false }
            }).on('resizemove', resizeListener);

        function dragMoveListener(event) {
            var target = event.target; 
            var index = parseInt(target.id.slice(6));
            rooms[index].fields.row_top += Math.round(event.dy / 40);
            rooms[index].fields.row_bottom += Math.round(event.dy / 40);
            appRef.setState({rooms: rooms});
        };
        
        function resizeListener(event) {
            var target = event.target; 
            var index = parseInt(target.id.slice(6));
            rooms[index].fields.row_bottom += Math.round(event.dy / 40);
            appRef.setState({rooms: rooms});
        };


    </script>
</body>
</html>